name: "appflowy_editor"

version: 5.2.0

homepage: "https://github.com/AppFlowy-IO/appflowy-editor"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.27.0"

description: A highly customizable rich-text editor for Flutter. The AppFlowy
  Editor project for AppFlowy and beyond.

dependencies:
  collection: "^1.18.0"
  device_info_plus: "^11.0.0"
  diff_match_patch: "^0.4.1"
  file_picker: "^8.0.2"
  flutter:
    sdk: flutter
  flutter_svg: "^2.0.6"
  html: ^0.15.5
  http: "^1.2.0"
  intl: "^0.20.2"
  keyboard_height_plugin: "^0.1.5"
  logging: "^1.2.0"
  markdown: "^7.2.1"
  nanoid: "^1.0.0"
  numerus: "^2.1.2"
  pdf: "^3.10.7"
  provider: "^6.0.5"
  scroll_to_index: "^3.0.1"
  string_validator: "^1.0.0"
  universal_html: "^2.2.4"
  universal_platform: ^1.1.0
  url_launcher: "^6.1.11"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_utils: "^2.8.2"
  mockito: "^5.4.1"
  network_image_mock: "^2.1.1"
  path_provider: "^2.0.5"
  pubspec_dependency_sorter: "^1.0.5"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - widgets
  - editor
  - appflowy

flutter:
  assets:
    - "assets/images/toolbar/"
    - "assets/images/selection_menu/"
    - "assets/images/image_toolbar/"
    - "assets/images/"
    - "assets/mobile/toolbar_icons/"

flutter_intl:
  enabled: true
  class_name: AppFlowyEditorLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/src/l10n
  use_deferred_loading: false
  localizely:
    project_id: b7199c7d-eca0-4025-894d-230cdcafa9aa
